# Generated by Django 5.0.7 on 2024-07-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(''),
    ]
