# Generated by Django 5.0.7 on 2024-07-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0002_auto_20240726_2347"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestTable",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "test_table",
                "managed": False,
            },
        ),
    ]
