# Generated by Django 5.0.7 on 2024-07-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("manufacturer", models.CharField(max_length=50)),
                ("style", models.CharField(max_length=50)),
                ("purchase_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("quantity_on_hand", models.IntegerField()),
                (
                    "commision_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "db_table": "Product",
                "managed": False,
            },
        ),
    ]
