# Generated by Django 5.0.7 on 2024-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salesperson",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("start_date", models.DateField()),
                ("termination_date", models.DateField()),
                ("manager", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Salesperson",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="TestTable",
        ),
    ]
