# Generated by Django 5.0.7 on 2024-07-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("start_date", models.DateField()),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("username", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "Salesperson",
                "managed": False,
            },
        ),
    ]
