# Generated by Django 5.0.7 on 2024-07-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_manager"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={"managed": False},
        ),
        migrations.AlterModelTable(
            name="manager",
            table="Manager",
        ),
    ]
