# Generated by Django 5.0.7 on 2024-07-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_discount_options_alter_sale_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="discount",
            table="Discount",
        ),
        migrations.AlterModelTable(
            name="sale",
            table="Sale",
        ),
    ]
